=== olmozavala/MapViewerInterface/DeepCProject/web/layers/schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="MenuConf"><!-- root element-->
  
  <xs:complexType mixed="true">
  <xs:sequence maxOccurs="unbounded"><!--childs of root, limited to 3 for now -->    
   
   
   
   <xs:element name="MenuEntries" minOccurs="0"><!--MenuEntries(root's child) level -->
       <xs:complexType mixed="true">
  
  <xs:sequence maxOccurs="unbounded"><!--infinite limit of MenuEntry numbers -->
      
      <xs:element name="MenuEntry" minOccurs="1"> <!--MenuEntry level -->
          <xs:complexType mixed="true">          
          <xs:attribute name="ID" type="xs:string" use="required"></xs:attribute>
          <xs:attribute name="EN" type="xs:string" use="required"></xs:attribute>
          <xs:attribute name="ES" type="xs:string" ></xs:attribute>
          </xs:complexType>                 
      </xs:element>       
      </xs:sequence>  
   </xs:complexType>
   </xs:element><!--end of MenuEntries -->
   
   <xs:element name="BackgroundLayers" minOccurs="0"> <!--BackgroundLayers (root's child) level -->
       
       <xs:complexType mixed="true">
           <!--different optional atributes of background layer -->
       
       <xs:sequence maxOccurs="unbounded">
       
        <xs:element name="layer" minOccurs="0"> <!--Menuconf/BackgroundLayers/layer -->
          <xs:complexType mixed="true">
          
          <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
         <xs:attribute name="title" type="xs:string"></xs:attribute>
          <xs:attribute name="BBOX" type="xs:string" />
           <xs:attribute name="format" type="xs:string" />
           <xs:attribute name="proj" type="xs:string" />
           <xs:attribute name="server" type="xs:string" />
           <xs:attribute name="palette" type="xs:string" />
           <xs:attribute name="trans_effect" type="xs:string" />
           <xs:attribute name="width" type="xs:string" />
           <xs:attribute name="height" type="xs:string" />
           <xs:attribute name="mincolor" type="xs:string" />
           <xs:attribute name="maxcolor" type="xs:string" />
           <xs:attribute name="tiled">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                      
           <xs:attribute name="time">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                      
           <xs:attribute name="style" type="xs:string" /> 
         </xs:complexType>
                  
      </xs:element><!-- End of Menuconf/BackgroundLayers/layer -->
       
       </xs:sequence>
          <!-- Attributes of BackgroundLayers -->
           <xs:attribute name="BBOX" type="xs:string" />
           <xs:attribute name="format" type="xs:string" />
           <xs:attribute name="proj" type="xs:string" />
           <xs:attribute name="server" type="xs:string" />
           <xs:attribute name="palette" type="xs:string" />
           <xs:attribute name="trans_effect" type="xs:string" />
           <xs:attribute name="width" type="xs:string" />
           <xs:attribute name="height" type="xs:string" />
           <xs:attribute name="mincolor" type="xs:string" />
           <xs:attribute name="maxcolor" type="xs:string" />
           <xs:attribute name="tiled">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                     
           <xs:attribute name="time">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute> 
       <xs:attribute name="style" type="xs:string" />  
       </xs:complexType>
       </xs:element> <!--End of BackgroundLayer -->
   
    <xs:element name="VectorLayers" minOccurs="0"> <!--VectorLayers (root's child) level -->
       
       <xs:complexType mixed="true">
                  
       <xs:sequence maxOccurs="unbounded">
       
        <xs:element name="layer" minOccurs="0"> <!--Menuconf/BackgroundLayers/layer -->
          <xs:complexType mixed="true">
          
          <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
          <xs:attribute name="Menu" type="xs:string"></xs:attribute>
          <xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
         <xs:attribute name="title" type="xs:string"></xs:attribute>
          <xs:attribute name="BBOX" type="xs:string" />
           <xs:attribute name="format" type="xs:string" />
           <xs:attribute name="proj" type="xs:string" />
           <xs:attribute name="server" type="xs:string" />
           <xs:attribute name="palette" type="xs:string" />
           <xs:attribute name="trans_effect" type="xs:string" />
           <xs:attribute name="width" type="xs:string" />
           <xs:attribute name="height" type="xs:string" />
           <xs:attribute name="mincolor" type="xs:string" />
           <xs:attribute name="maxcolor" type="xs:string" />
           <xs:attribute name="tiled">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                      
           <xs:attribute name="time">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                      
           <xs:attribute name="style" type="xs:string" /> 
         </xs:complexType>
                  
      </xs:element><!-- End of Menuconf/VectorLayers/layer -->
       
       </xs:sequence>
          <!-- Attributes of VectorLayers -->
           <xs:attribute name="BBOX" type="xs:string" />
           <xs:attribute name="format" type="xs:string" />
           <xs:attribute name="proj" type="xs:string" />
           <xs:attribute name="server" type="xs:string" />
           <xs:attribute name="palette" type="xs:string" />
           <xs:attribute name="trans_effect" type="xs:string" />
           <xs:attribute name="width" type="xs:string" />
           <xs:attribute name="height" type="xs:string" />
           <xs:attribute name="mincolor" type="xs:string" />
           <xs:attribute name="maxcolor" type="xs:string" />
           <xs:attribute name="tiled">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                     
           <xs:attribute name="time">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute> 
       <xs:attribute name="style" type="xs:string" />  
       </xs:complexType>
       </xs:element> <!--End of VectorLayer -->
   
   
    <xs:element name="MainLayers" minOccurs="0"> <!--MainLayers (root's child) level -->
       
       <xs:complexType mixed="true">
                  
       <xs:sequence maxOccurs="unbounded">
       
        <xs:element name="layer" minOccurs="0"> <!--Menuconf/MainLayers/layer -->
          <xs:complexType mixed="true">
          
          <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
          <xs:attribute name="Menu" type="xs:string"></xs:attribute>
          <xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
         <xs:attribute name="title" type="xs:string"></xs:attribute>
         <xs:attribute name="EN" type="xs:string"></xs:attribute>
          <xs:attribute name="ES" type="xs:string"></xs:attribute>
          <xs:attribute name="BBOX" type="xs:string" />
           <xs:attribute name="format" type="xs:string" />
           <xs:attribute name="proj" type="xs:string" />
           <xs:attribute name="server" type="xs:string" />
           <xs:attribute name="palette" type="xs:string" />
           <xs:attribute name="trans_effect" type="xs:string" />
           <xs:attribute name="width" type="xs:string" />
           <xs:attribute name="height" type="xs:string" />
           <xs:attribute name="mincolor" type="xs:string" />
           <xs:attribute name="maxcolor" type="xs:string" />
           <xs:attribute name="tiled">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                      
           <xs:attribute name="time">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                      
           <xs:attribute name="style" type="xs:string" /> 
             
             
             <xs:attribute name="max_time_range">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="week" /> 
                       <xs:enumeration value="month" />
                       <xs:enumeration value="year" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                      
             
             
         </xs:complexType>
                  
      </xs:element><!-- End of Menuconf/MainLayers/layer -->
       
       </xs:sequence>
          <!-- Attributes of MainLayers -->
           <xs:attribute name="BBOX" type="xs:string" />
           <xs:attribute name="format" type="xs:string" />
           <xs:attribute name="proj" type="xs:string" />
           <xs:attribute name="server" type="xs:string" />
           <xs:attribute name="palette" type="xs:string" />
           <xs:attribute name="trans_effect" type="xs:string" />
           <xs:attribute name="width" type="xs:string" />
           <xs:attribute name="height" type="xs:string" />
           <xs:attribute name="mincolor" type="xs:string" />
           <xs:attribute name="maxcolor" type="xs:string" />
           <xs:attribute name="tiled">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>                     
           <xs:attribute name="time">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="true" /> 
                       <xs:enumeration value="false" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute> 
       <xs:attribute name="style" type="xs:string" />  
               <xs:attribute name="max_time_range">
               <xs:simpleType>
                   <xs:restriction base="xs:string">
                       <xs:enumeration value="week" /> 
                       <xs:enumeration value="month" />
                       <xs:enumeration value="bimonth" />
                       <xs:enumeration value="year" />                                                           
                   </xs:restriction> 
                </xs:simpleType>
           </xs:attribute>   
       
       
       
       
       </xs:complexType>
       
       
       
       
       
       </xs:element> <!--End of MainLayer -->
   
   
   
   
   </xs:sequence>
  </xs:complexType>
</xs:element><!-- end of root element -->

</xs:schema>

=== olmozavala/MapViewerInterface/DeepCProject/web/layers/CommonMenus.xml
<MenuConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<MenuEntries>
		<MenuEntry ID="2012" EN="2012" ES="2012"/>
		<MenuEntry ID="2011" EN="2011" ES="2011"/>
		<MenuEntry ID="2010" EN="2010" ES="2010"/>
		<MenuEntry ID="Jan" EN="January" ES="Enero"/>
		<MenuEntry ID="Feb" EN="February" ES="Febrero"/>
		<MenuEntry ID="Mar" EN="March" ES="Marzo"/>
		<MenuEntry ID="Apr" EN="April" ES="Abril"/>
		<MenuEntry ID="May" EN="May" ES="Mayo"/>
		<MenuEntry ID="Jun" EN="June" ES="Junio"/>
		<MenuEntry ID="Jul" EN="July" ES="Julio"/>
		<MenuEntry ID="Ago" EN="August" ES="Agosto"/>
		<MenuEntry ID="Sep" EN="September" ES="Septiembre"/>
		<MenuEntry ID="Oct" EN="October" ES="Octubre"/>
		<MenuEntry ID="Nov" EN="November" ES="Noviembre"/>
		<MenuEntry ID="Dec" EN="December" ES="Diciembre"/>

		<!--Cruises related-->
		<MenuEntry ID="cruises" EN="Cruises" ES="Cruceros"/>
		<MenuEntry ID="etype" EN="Event type" ES="Tipo de evento"/>
		<MenuEntry ID="allsites" EN="All sites" ES="Todos los sitios"/>
		<MenuEntry ID="allcruises" EN="All cruises" ES="Todos los cruceros"/>

		<!--Ocean models related-->
		<MenuEntry ID="omodel" EN="Ocean models" ES="Modelos oceano"/>
		<MenuEntry ID="hycom" EN="HYCOM" ES="HYCOM"/>
		<MenuEntry ID="Temp" EN="Temperature" ES="Temperatura"/>
		<MenuEntry ID="SurfTemp" EN="Temperature Trend" ES="Tendencia de Temp.`"/>
		<MenuEntry ID="Salinity" EN="Salinity" ES="Salinidad"/>
		<MenuEntry ID="SeaElev" EN="Elevation" ES="Elevacion"/>
		<MenuEntry ID="SeaVel" EN="Velocity" ES="Velocidad"/>

		<!--Extra titles -->
		<MenuEntry ID="mx_st" EN="Mexico States" 		ES="Estados de Mexico"/>
		<MenuEntry ID="us_st" EN="US States" 		ES="Estados de USA"/>
		<MenuEntry ID="deep" EN="DeepC" 		ES="DeepC"/>
		<MenuEntry ID="gebco" EN="GEBCO Bathymetry" ES="Batimetria de GEBCO"/>

		<MenuEntry ID="test" EN="TEST" 		ES="TEST"/>
		<MenuEntry ID="test2" EN="TEST2" 		ES="TEST"/>
		<MenuEntry ID="test3" EN="USGS Test" 		ES="TEST"/>
	</MenuEntries>
</MenuConf>
